server:
  port: 8081

spring:
  application:
    name: ClientService1

    
eureka:
  instance:
    status-page-url-path: /
    health-check-url-path: /actuator/health


management:
  endpoints:
    web:
      exposure:
        include: refresh

message: Hello from Service 1000100
